import { GoogleGenAI } from '@google/genai';
import type { ChatMessage } from '../types';
import { isRetriableModelError } from './engine';

const useVertex = process.env.VERTEX === 'true';

// Nano Banana 2 preview on Vertex AI requires the global location to function natively
const ai = useVertex
  ? new GoogleGenAI({ 
    vertexai: true, 
    apiKey: process.env.VERTEX_API_KEY || '',
  })
  : new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });

/**
 * Nano Banana 2 Progress Handler
 * Simulates a smooth progress bar based on average 8s generation time.
 */
class BananaProgress {
  private progress = 0;
  private interval: any = null;

  constructor(private onUpdate: (pct: number) => void) {}

  start() {
    this.progress = 0;
    // Simulate fast progress to 30%, then slow down to 90%
    this.interval = setInterval(() => {
      if (this.progress < 30) {
        this.progress += 5;
      } else if (this.progress < 85) {
        this.progress += 2;
      } else if (this.progress < 95) {
        this.progress += 0.5;
      }
      this.onUpdate(Math.floor(this.progress));
    }, 400); // Update every 400ms
  }

  complete() {
    if (this.interval) clearInterval(this.interval);
    this.onUpdate(100);
  }

  stop() {
    if (this.interval) clearInterval(this.interval);
  }
}

export const generateSceneImage = async (
  prompt: string, 
  onProgress?: (progress: number, interimImageUrl?: string) => void,
  onRetry?: (seconds: number, attempt: number, status: string) => void,
  externalAbortSignal?: AbortSignal
): Promise<Omit<ChatMessage, 'id' | 'timestamp'>> => {
  const bar = new BananaProgress((pct) => onProgress?.(pct));
  let attempt = 0;
  let transientRetryCount = 0;

  while (true) {
    const abortController = new AbortController();
    
    // If external abort signal is provided, hook it up
    if (externalAbortSignal) {
      externalAbortSignal.addEventListener('abort', () => {
        abortController.abort();
      });
    }
    
    let timedOut = false;
    const timeout = setTimeout(() => {
      timedOut = true;
      abortController.abort();
    }, 120000); // Increased from 45s to 120s (2m)

    try {
      bar.start();
      
      // gemini-3.1-flash-image-preview is a Gemini model, which requires the generateContent API
      // with a response modality explicitly set to ['IMAGE']
      const response = await ai.models.generateContent({
        model: 'gemini-3.1-flash-image-preview', 
        contents: prompt, 
        config: {
          responseModalities: ['IMAGE'],
          // We must cast these as 'any' for now since the SDK types frequently lag behind the preview API schema
          imageConfig: {
            aspectRatio: '16:9',
            imageSize: '512', // Explicitly use "512" (not "0.5K" or "512px") to trigger the high-speed 0.5K tier
          } as any,
          thinkingConfig: {
            thinkingLevel: 'minimal', // Forces the absolute lowest token reasoning floor
            includeThoughts: true,    // Required to extract and audit the token count
          } as any,
          abortSignal: abortController.signal,
        } as any
      });

      bar.complete();

      // Audit extraction: parse out the hidden reasoning strings to calculate the thought budget size
      const thoughtParts = response.candidates?.[0]?.content?.parts?.filter((p: any) => p.thought && typeof p.text === 'string') || [];
      const combinedThoughts = thoughtParts.map((p: any) => p.text).join('');
      const thoughtLength = combinedThoughts.length;

      const part = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
      if (!part || !part.inlineData) {
        throw new Error('No image generated by the model.');
      }

      const base64Image = part.inlineData.data;
      const mimeType = part.inlineData.mimeType || 'image/jpeg';

      return {
        type: 'image',
        text: prompt,
        imageUrl: `data:${mimeType};base64,${base64Image}`,
        thoughtLength, // Passes the audited latency footprint to the UI
      };
    } catch (err: any) {
      bar.stop();
      clearTimeout(timeout);

      const errorToCheck = timedOut ? new Error('MODEL_IMAGE_TIMEOUT') : err;
      const isRetryable = isRetriableModelError(errorToCheck);

      if (isRetryable) {
        let status = errorToCheck?.status || errorToCheck?.response?.status;
        if (!status && typeof errorToCheck.message === 'string') {
          const match = errorToCheck.message.match(/\b(503|500|429)\b/);
          if (match) status = match[1];
        }
        const statusStr = status ? String(status) : (timedOut ? 'TIMEOUT' : 'Unknown');

        transientRetryCount += 1;
        attempt += 1;
        const backoffSeconds = Math.min(Math.pow(2, transientRetryCount), 10);
        onRetry?.(backoffSeconds, attempt, statusStr);
        await new Promise((resolve) => setTimeout(resolve, backoffSeconds * 1000));
        continue;
      }

      throw errorToCheck;
    } finally {
      clearTimeout(timeout);
    }
  }
};